---
abstract: 'export RDF data to Atom'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
keywords:
  - ActivityStrea.ms
  - Atom
  - Feed
  - OWL
  - RDF
  - 'Semantic Web'
  - Syndication
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: XML::Atom::FromOWL
name: XML-Atom-FromOWL
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Data::UUID: 0
  RDF::TrineX::Functions: 0
  XML::Atom: 0
  XML::LibXML: 1.94
  namespace::clean: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=XML-Atom-FromOWL
  homepage: https://metacpan.org/release/XML-Atom-FromOWL
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/svn-web/perlmods/browse/XML-Atom-FromOWL/
version: 0.101
